text = """
  "action_jester_desc": "Wähle eine der drei Karten, um deine Gaukler-Rolle für diese Nacht damit zu tauschen. 🤡🎴🌙",
  "action_love_btn": "Zur Handlung 💘",
  "action_love_desc": "Wähle zwei Spieler aus der Liste aus, die sich verlieben sollen. Stirbt einer, stirbt der andere auch. 💑💔",
  "action_maid_btn": "Zur Handlung 👩‍🌾",
  "action_maid_desc": "Wähle einen Spieler, dessen Rolle die Ergebene Magd übernehmen soll. Dieser Spieler stirbt. 👩‍🌾💀",
  "action_orphan_btn": "Zur Handlung 👶",
  "action_orphan_desc": "Wähle ein Vorbild aus. Das Waisenkind wird dessen Rolle annehmen. 👶➡️🎭",
  "action_thief_desc": "Wähle eine der beiden Karten, um deine Diebes-Rolle damit zu tauschen. 🕵️‍♂️🎴",
  "action_urwolf_btn": "Zur Handlung 🐺",
  "action_urwolf_desc": "Wähle einen Spieler aus, der zu einem Werwolf wird. 🐺➡️",
  "all_roles_revealed": "Alle Rollen aufgedeckt 👀🎭",
  "back": "Zurück 🔙",
  "card_reveal_title": "Rollen aufdecken 🃏",
  "change_roles": "Rollen verändern 🔄",
  "confirm": "Bestätigen ✅",
  "confirm_jester_desc": "Du hast den Gaukler ausgewählt. Du musst nun 3 zusätzliche Rollen für ihn auswählen. 🤡🎭 (3 auswählen)",
  "confirm_jester_title": "Gaukler ausgewählt 🤡",
  "confirm_thief_desc": "Du hast den Dieb ausgewählt. Du musst nun 2 zusätzliche Rollen für ihn auswählen. 🕵️‍♂️🎭 (2 auswählen)",
  "confirm_thief_title": "Dieb ausgewählt 🕵️‍♂️",
  "continue": "Weiter ▶️",
  "continue_to_jester": "Weiter zum Gaukler 🤡",
  "day_bear_growl": "GRRRR! Der Bär knurrt! 🐻",
  "day_deaths_of_day_none": "Niemand ist am Tag gestorben 😌",
  "day_deaths_of_day_title": "Tote des Tages 💀",
  "day_deaths_title": "Die Nacht ist vorbei. Folgende Personen sind gestorben: 💀",
  "day_discussion_desc": "Diskutiert jetzt, wer der Werwolf sein könnte 🗣️🐺",
  "day_discussion_title": "Diskussionsphase 🗨️",
  "day_hunter_choose_target": "Wähle ein Ziel für deinen letzten Schuss 🎯🔫",
  "day_hunter_shoots_title": "Der Jäger schießt 🔫",
  "day_judge_decision_desc": "Soll eine zweite Abstimmung stattfinden? ⚖️",
  "day_judge_decision_title": "Stotternder Richter 👨‍⚖️",
  "day_judge_no": "Nein ❌",
  "day_judge_second_vote_no": "Es gibt keine zweite Abstimmung. ❌",
  "day_judge_second_vote_yes": "Der Richter hat eine zweite Abstimmung angeordnet! ⚖️👨‍⚖️",
  "day_judge_yes": "Ja ✅",
  "day_maid_choice_desc": "Möchtest du die Rolle eines Verstorbenen übernehmen? 🎭💀",
  "day_maid_choice_title": "Ergebene Magd 👩‍🌾",
  "day_maid_nothing": "Nichts tun ⛔",
  "day_no_deaths": "Diese Nacht ist niemand gestorben. 🌙🙂",
  "day_second_voting_desc": "Wählt gemeinsam eine Person aus (keine Diskussion!) ⚖️🚫🗣️",
  "day_second_voting_title": "Zweite Abstimmung ⚖️",
  "day_voting_desc": "Wählt gemeinsam eine Person aus 👥",
  "day_voting_scapegoat": "Gleichstand - Sündenbock stirbt ⚖️🐑💀",
  "day_voting_title": "Erste Abstimmung ⚖️",
  "explanation": "Erklärung 📖",
  "give_to_narrator": "Bitte übergib das Gerät jetzt an den Erzähler. 📱🎙️",
  "home_description": "Hier kannst du einfach die Rollen für dein Werwolf-Spiel verteilen und sie dir erklären lassen. 🎭🐺📖",
  "home_welcome": "Willkommen bei dem Werwolf-Spiel von Thomas. 👋🎉",
  "homepage_info": "Kompletter Reset ♻️",
  "jester": "Gaukler 🤡",
  "jester_selection_title": "Wähle 3 Rollen für den Gaukler 🎭🤡",
  "language": "Sprache 🌐",
  "love": "Verlieben 💘",
  "lovers_modal_btn": "Markierung entfernen? ❌",
  "lovers_modal_desc": "Möchtest du die aktuelle Markierung der Verliebten aufheben, um zwei neue Spieler zu verlieben? 💑🔁",
  "lovers_modal_title": "Verliebte 💑",
  "maid": "Magd 👩‍🌾",
  "n_roles_to_assign": "Noch {count} Rollen zu vergeben 🎭",
  "narrator_alle_buerger_close_eyes": "Alle Bürger, schließt jetzt bitte eure Augen. 🙈",
  "narrator_alle_buerger_open_eyes": "Alle Bürger öffnen jetzt ihre Augen. 👀",
  "narrator_amor_text": "Amor, du darfst deine Augen jetzt öffnen.<br>Wähle zwei Personen aus, die du verkuppeln möchtest.<br>(Amor zeigt auf zwei Personen)<br>Amor, schließe jetzt deine Augen.<br>Ich gehe jetzt rum und tippe die beiden Verliebten an.<br>(Erzähler geht rum und tippt die beiden Verliebten an)<br>Verliebten, ihr dürft jetzt eure Augen öffnen und euch gegenseitig sehen.<br>(Verliebten schauen sich an)<br>Verliebten, schließt eure Augen bitte wieder. 💘",
  "narrator_cannot_heal_same_twice": "Du kannst nicht dieselbe Person zweimal hintereinander heilen 🔁🚫",
  "narrator_cannot_select_werewolves": "Du kannst keine Werwölfe auswählen 🐺🚫",
  "narrator_cannot_select_yourself": "Du kannst dich nicht selbst auswählen 🙅‍♂️",
  "narrator_das_wilde_kind_text": "Wildes Kind, du darfst deine Augen jetzt öffnen.<br>Wähle eine Person aus, die dein Vorbild sein soll.<br>Wenn dein Vorbild stirbt, wirst du zum Werwolf.<br>(Das wilde Kind zeigt auf eine Person)<br>Wildes Kind, schließe jetzt deine Augen. 🧒➡️🐺",
  "narrator_day_angel_wins": "Der Engel ist in der ersten Abstimmung gestorben. Der Engel gewinnt! 😇🏆",
  "narrator_day_angel_wins_vote": "Der Engel stirbt! Der Engel gewinnt! 😇🏆",
  "narrator_day_codewort_spoken": "Das Codewort wurde gesagt - Zweite Abstimmung! 🔑⚖️",
  "narrator_day_deaths_title": "Die Nacht ist vorbei. Folgende Personen sind gestorben: 💀",
  "narrator_day_discussion": "Diskussionsphase: Besprecht euch, wer der Werwolf sein könnte. 🗣️🐺",
  "narrator_day_dorfdepp": "Der Dorfdepp darf nicht sterben, aber verliert sein Abstimmungsrecht. 🤡❌🗳️",
  "narrator_day_dorfdepp_cannot_die": "Der Dorfdepp darf nicht sterben, verliert aber sein Stimmrecht 🤡🚫🗳️",
  "narrator_day_hunter_shoots": "Der Jäger ist gestorben. Mit deinem letzten Atemzug schießt du noch einen Schuss ab. 🔫💀",
  "narrator_day_hunter_shoots_before_death": "Der Jäger schießt vor dem Tod 🔫",
  "narrator_day_lover_dies_too": "Ein Verliebter stirbt - der andere auch! 💔💀",
  "narrator_day_maid_button": "👩🏼 Ergebene Magd",
  "narrator_day_maid_choice": "Ergebene Magd, möchtest du die Rolle eines Verstorbenen übernehmen? 👩‍🌾🎭💀",
  "narrator_day_maid_role_reveal": "Gerät an die Ergebene Magd übergeben - Rolle aufdecken 📱➡️👩‍🌾🃏",
  "narrator_day_maid_select_dead": "Wähle einen Verstorbenen zur Rollenübernahme ⚰️➡️👩‍🌾",
  "narrator_day_no_deaths": "Diese Nacht ist niemand gestorben. 🌙🙂",
  "narrator_day_scapegoat": "Gleichstand - Sündenbock stirbt! ⚖️🐑💀",
  "narrator_day_second_vote": "Zweite Abstimmung: Das Codewort des Richters wurde gesagt. 🔁👨‍⚖️",
  "narrator_day_voting": "Abstimmungsphase: Wählt eine Person aus, die ihr anklagen möchtet. 🗳️",
  "narrator_day_voting_select": "Wähle eine Person zur Abstimmung 👤🗳️",
  "narrator_day_voting_tie": "Es gibt einen Gleichstand. Der Sündenbock stirbt sofort. ⚖️🐑💀",
  "narrator_der_fuchs_text_1": "Fuchs, du darfst deine Augen jetzt öffnen.<br>Wähle eine Person aus.<br>Ich werde dir zeigen, ob sie oder einer ihrer beiden Nachbarn ein Werwolf ist.<br>Wenn einer ein Werwolf ist zeige ich einen Daumen nach oben.<br>Wenn keiner ein Werwolf ist zeige ich einen Daumen nach unten<br>und du verlierst deine Fähigkeit.<br>(Der Fuchs zeigt auf eine Person)<br>(Erzähler zeigt, ob im Trio ein Werwolf ist oder nicht)<br>Fuchs, schließe jetzt deine Augen. 🦊👀",
  "narrator_der_fuchs_text_2": "Fuchs, du darfst deine Augen jetzt öffnen.<br>Wähle eine Person aus.<br>Ich werde dir zeigen, ob sie oder einer ihrer beiden Nachbarn ein Werwolf ist.<br>Wenn einer ein Werwolf ist zeige ich einen Daumen nach oben.<br>Wenn keiner ein Werwolf ist zeige ich einen Daumen nach unten<br>und du verlierst deine Fähigkeit.<br>(Der Fuchs zeigt auf eine Person)<br>(Erzähler zeigt, ob im Trio ein Werwolf ist oder nicht)<br>Fuchs, schließe jetzt deine Augen. 🦊👀",
  "narrator_der_grosse_boese_werwolf_text": "(nur jede zweite Nacht aufrufen)<br>Großer böser Werwolf, öffne deine Augen.<br>Wähle noch ein zweites Opfer, das du in dieser Nacht töten möchtest.<br>(Der große böse Werwolf zeigt auf ein Opfer)<br>Großer böser Werwolf, schließe nun deine Augen. 🐺⚔️",
  "narrator_der_obdachlose_text_1": "Obdachloser, du darfst deine Augen jetzt öffnen.<br>Suche dir eine Person aus, bei der du übernachten möchtest.<br>Wenn die Person in der Nacht von den Werwölfen gefressen wird, stirbst du auch.<br>Du darfst nicht zwei Nächte bei einer Person schlafen.<br>(Der Obdachlose zeigt auf eine Person)<br>Obdachlose, schließe jetzt deine Augen. 🛌🚫",
  "narrator_der_obdachlose_text_2": "Obdachloser, du darfst deine Augen jetzt öffnen.<br>Suche dir eine Person aus, bei der du übernachten möchtest.<br>Wenn die Person in der Nacht von den Werwölfen gefressen wird, stirbst du auch.<br>Du darfst nicht zwei Nächte bei einer Person schlafen.<br>(Der Obdachlose zeigt auf eine Person)<br>Obdachlose, schließe jetzt deine Augen. 🛌🚫",
  "narrator_der_stotternde_richter_text": "Richter, du darfst deine Augen jetzt öffnen.<br>Zeige mir ein geheimes kleines Zeichen, welches du machst,<br>wenn am heutigen Tag eine zweite Abstimmung stattfinden soll.<br>(Der Richter und der Erzähler vereinbaren ein geheimes Zeichen)<br>Richter, schließe jetzt deine Augen. 🤫👨‍⚖️",
  "narrator_der_verbitterte_greis_text": "Verbitterte Greis, du darfst deine Augen jetzt öffnen.<br>Teile unsere Gruppe in zwei kleinere gleichgroße Gruppen auf.<br>(Z.B. in dunkle Haare und helle Haare)<br>Wird eine dieser Gruppen eliminiert und du lebst noch gewinnst du.<br>(Der verbitterte Greis macht zwei Gruppen)<br>Du darfst deine Augen wieder schließen. 👴⚖️",
  "narrator_der_weisse_werwolf_text": "(nur jede zweite Nacht aufrufen)<br>Weißer Werwolf, du darfst jetzt deine Augen öffnen.<br>Welchen deiner Werwolf-Kollegen möchtest du töten?<br>(Der weiße Werwolf zeigt auf einen Werwolf)<br>Weißer Werwolf, schließe jetzt deine Augen. 🐺⚪",
  "narrator_der_wolfshund_text": "Wolfshund, du darfst deine Augen jetzt öffnen.<br>Ich halte die beiden Hände hoch, die rechte Hand bedeutet Werwolf<br>und die linke Hand bedeutet Dorfbewohner.<br>(Erzähler hält beide Hände hoch)<br>Entscheide dich was du sein willst.<br>(Der Wolfshund zeigt auf einen der Hände)<br>Wolfshund, schließe jetzt deine Augen. 🐶✋",
  "narrator_die_drei_brueder_text": "Brüder, ihr dürft eure Augen jetzt öffnen.<br>Schaut euch an, damit ihr euch erkennt.<br>(Die drei Brüder schauen sich an)<br>Brüder, schließt bitte wieder die Augen. 👬👬",
  "narrator_die_zwei_schwestern_text": "Schwestern, ihr dürft eure Augen jetzt öffnen.<br>Schaut euch an, damit ihr euch erkennt.<br>(Die zwei Schwestern schauen sich an)<br>Schwestern, schließt bitte wieder die Augen. 👭",
  "narrator_dieb_text": "Dieb, du darfst deine Augen jetzt öffnen.<br>Ich halte jetzt die zwei übrigen Rollen in der Hand.<br>Du kannst nun deine Rolle mit einer der beiden Rollen tauschen oder deine Rolle behalten.<br>(Erzähler hält die zwei übrigen Karten hoch)<br>Wenn du deine Rolle behältst, bleibst du ein Dorfbewohner.<br>Wenn du eine neue Karte willst, zeig drauf.<br>(Erzähler nimmt die Karte, die der Dieb nicht will, weg)<br>Dieb, schließe jetzt deine Augen. 🃏🕵️‍♂️",
  "narrator_floetenspieler_text_1": "Flötenspieler, du darfst jetzt deine Augen öffnen.<br>Wähle jetzt zwei Personen aus, die du mit deiner Musik verzaubern möchtest.<br>(Der Flötenspieler zeigt auf zwei Personen)<br>Flötenspieler, schließe jetzt deine Augen.<br>Ich tippe jetzt die Verzauberten an.<br>(Erzähler geht rum und tippt die Verzauberten an)<br>Verzauberten ihr dürft jetzt aufwachen<br>und euch mit Handzeichen besprechen wer der Flötenspieler ist.<br>Wenn der Flötenspieler alle Personen verzaubert hat, gewinnt er.<br>Verzauberten ihr dürft eure Augen jetzt schließen. 🎶🪄",
  "narrator_floetenspieler_text_2": "Flötenspieler, du darfst jetzt deine Augen öffnen.<br>Wähle jetzt zwei Personen aus, die du mit deiner Musik verzaubern möchtest.<br>(Der Flötenspieler zeigt auf zwei Personen)<br>Flötenspieler, schließe jetzt deine Augen.<br>Ich tippe jetzt die Verzauberten an.<br>(Erzähler geht rum und tippt die Verzauberten an)<br>Verzauberten ihr dürft jetzt aufwachen<br>und euch mit Handzeichen besprechen wer der Flötenspieler ist.<br>Wenn der Flötenspieler alle Personen verzaubert hat, gewinnt er.<br>Verzauberten ihr dürft eure Augen jetzt schließen. 🎶🪄",
  "narrator_fuchs_no_werewolf": "Keiner von den drei ist ein Werwolf. Du hast deine Fähigkeit verloren. ❌🦊",
  "narrator_fuchs_werewolf_found": "Mindestens einer von den drei ist ein Werwolf! ✅🦊",
  "narrator_game_end_angel_wins": "Der Engel hat gewonnen! 😇🏆",
  "narrator_game_end_bitter_old_man_wins": "Der verbitterte Greis hat gewonnen! 👴🏆",
  "narrator_game_end_lovers_win": "Die Verliebten haben gewonnen! 💑🏆",
  "narrator_game_end_piper_wins": "Der Flötenspieler hat gewonnen! 🎶🏆",
  "narrator_game_end_villagers_win": "Die Dorfbewohner haben gewonnen! 🏘️🏆",
  "narrator_game_end_werewolves_win": "Die Werwölfe haben gewonnen! 🐺🏆",
  "narrator_game_end_white_wolf_wins": "Der weiße Werwolf hat alleine gewonnen! 🐺⚪🏆",
  "narrator_game_start_button": "Zum Start ▶️",
  "narrator_game_start_listening": "Der Erzähler spricht gleich. Höre aufmerksam zu... 🎙️👂",
  "narrator_game_start_ready": "Bereit? Drücke auf \"Zum Start\" ✅",
  "narrator_game_start_title": "Spiel starten 🕹️",
  "narrator_game_start_waiting": "Audio wird abgespielt... 🔊",
  "narrator_gaukler_text_1": "Gaukler, du darfst deine Augen jetzt öffnen.<br>Ich halte jetzt die drei für dich ausgewählten Rollen in der Hand.<br>Du kannst dich jetzt entscheiden welche Rolle du für diese Nacht spielen möchtest.<br>(Der Gaukler zeigt auf einer der Rollen)<br>Gaukler schließe deine Augen. 🤡🎴",
  "narrator_gaukler_text_2": "Gaukler, du darfst deine Augen jetzt öffnen.<br>Ich halte jetzt die drei für dich ausgewählten Rollen in der Hand.<br>Du kannst dich jetzt entscheiden welche Rolle du für diese Nacht spielen möchtest.<br>(Der Gaukler zeigt auf einer der Rollen)<br>Gaukler schließe deine Augen. 🤡🎴",
  "narrator_heiler_beschuetzer_text_1": "Heiler/Beschützer, du darfst jetzt deine Augen öffnen.<br>Wähle eine Person aus, die du beschützen möchtest.<br>Diese Person wird egal durch was sie getötet werden würde nicht sterben.<br>Du darfst keine Person zweimal hintereinander beschützen.<br>(Heiler zeigt auf die Person)<br>Heiler/Beschützer, schließe jetzt deine Augen. 🩺🛡️",
  "narrator_heiler_beschuetzer_text_2": "Heiler/Beschützer, du darfst jetzt deine Augen öffnen.<br>Wähle eine Person aus, die du beschützen möchtest.<br>Diese Person wird egal durch was sie getötet werden würde nicht sterben.<br>Du darfst keine Person zweimal hintereinander beschützen.<br>(Heiler zeigt auf die Person)<br>Heiler/Beschützer, schließe jetzt deine Augen. 🩺🛡️",
  "narrator_hexe_heal_button": "Heiltrank 🧪",
  "narrator_hexe_heal_used": "Heiltrank bereits benutzt ❌🧪",
  "narrator_hexe_nothing_button": "Nichts tun ⛔",
  "narrator_hexe_poison_button": "Gifttrank 🧪☠️",
  "narrator_hexe_poison_used": "Gifttrank bereits benutzt ❌☠️",
  "narrator_hexe_text_1": "Hexe, du darfst deine Augen jetzt öffnen.<br>Das ist das Opfer der Werwölfe.<br>(Erzähler zeigt der Hexe, wer das Opfer der Werwölfe ist)<br>Möchtest du es mit deinem Heiltrank retten oder nicht?<br>Wenn ja mache einen Daumen nach oben.<br>Möchtest du noch jemanden töten?<br>Wenn ja mache einen Daumen nach unten.<br>Oder wenn du nichts tun möchtest<br>Mache einen Daumen in die Mitte.<br>Du darfst auch beide Tränke in der Nacht aufbrauchen.<br>(Die Hexe bewegt ihren Daumen)<br>Hexe, schließe jetzt deine Augen. 🧙‍♀️🧪",
  "narrator_hexe_text_2": "Hexe, du darfst deine Augen jetzt öffnen.<br>Das ist das Opfer der Werwölfe.<br>(Erzähler zeigt der Hexe, wer das Opfer der Werwölfe ist)<br>Möchtest du es mit deinem Heiltrank retten oder nicht?<br>Wenn ja mache einen Daumen nach oben.<br>Möchtest du noch jemanden töten?<br>Wenn ja mache einen Daumen nach unten.<br>Oder wenn du nichts tun möchtest<br>Mache einen Daumen in die Mitte.<br>Du darfst auch beide Tränke in der Nacht aufbrauchen.<br>(Die Hexe bewegt ihren Daumen)<br>Hexe, schließe jetzt deine Augen. 🧙‍♀️🧪",
  "narrator_mode_active": "Erzähler-Modus aktiv 🎙️",
  "narrator_mode_description": "Möchtest du mit oder ohne automatischen Erzähler spielen? 🤖🎙️",
  "narrator_mode_error_message": "Bitte mindestens einen Bösewicht auswählen (Werwolf, großer böser Werwolf, weißer Werwolf) 🐺⚠️",
  "narrator_mode_error_title": "Fehler: Keine Bösewichte ⚠️",
  "narrator_mode_title": "Spielmodus auswählen 🎮",
  "narrator_pause_auto": "⏸️ Pause... (überspring mit Weiter) ▶️",
  "narrator_piper_already_enchanted": "Diese Personen sind bereits verzaubert und können nicht erneut gewählt werden ✨🚫",
  "narrator_reine_seele_text_1": "Reine Seele, du darfst dich jetzt allen Dorfbewohnern zu erkennen geben.<br>(Die reine Seele gibt sich zu erkennen)<br>(Sobald das geschehen ist) 😇",
  "narrator_round_1": "1. Runde Text 1️⃣",
  "narrator_round_2": "2. Runde Text 2️⃣",
  "narrator_seating_info_message": "Bitte setzt euch in der Reihenfolge hin, in der die Karten verteilt wurden. 🪑",
  "narrator_seating_info_title": "Wichtige Information ℹ️",
  "narrator_seherin_text_1": "Seherin, du darfst deine Augen jetzt öffnen.<br>Wähle eine Person aus, von der du die Rolle sehen möchtest.<br>(Die Seherin zeigt auf eine Person)<br>(Erzähler tippt auf das I neben der Rolle der Person und zeigt sie der Seherin)<br>Seherin, schließe jetzt deine Augen. 🔮",
  "narrator_seherin_text_2": "Seherin, du darfst deine Augen jetzt öffnen.<br>Wähle eine Person aus, von der du die Rolle sehen möchtest.<br>(Die Seherin zeigt auf eine Person)<br>(Erzähler tippt auf das I neben der Rolle der Person und zeigt sie der Seherin)<br>Seherin, schließe jetzt deine Augen. 🔮",
  "narrator_select_amor_first": "Wähle die erste verliebte Person 💘",
  "narrator_select_amor_second": "Wähle die zweite verliebte Person 💘",
  "narrator_select_big_bad_wolf": "Wähle ein 2. Opfer (nicht andere Werwölfe) 🐺❌",
  "narrator_select_dieb_cards": "Wähle eine der 2 Karten 🃏",
  "narrator_select_exactly_half": "Wähle genau die Hälfte der Spieler 1/2 ⚖️",
  "narrator_select_fuchs": "Wähle eine Person zum Prüfen 🦊",
  "narrator_select_gaukler_cards": "Wähle eine der 3 Rollen 🎭",
  "narrator_select_greis_half": "Wähle genau die Hälfte aller Spieler 1/2 ⚖️",
  "narrator_select_heiler": "Wähle eine Person zum Beschützen 🩺🛡️",
  "narrator_select_hexe_action": "Heiltrank / Gifttrank / Nichts tun 🧪☠️⛔",
  "narrator_select_homeless": "Wähle eine Person, bei der du übernachtest 🛌",
  "narrator_select_piper": "Wähle 2 Personen zum Verzaubern 🎶✨",
  "narrator_select_richter_codeword": "Gib dein geheimes Codewort ein 🔐",
  "narrator_select_seherin": "Wähle eine Person, deren Rolle du sehen möchtest (nicht dich selbst) 🔮",
  "narrator_select_urwolf": "Wähle eine Person zu infizieren 🐺➡️",
  "narrator_select_waisenkind": "Wähle ein Vorbild aus (nicht dich selbst) 👶➡️",
  "narrator_select_werwolf": "Wähle eine Person zu töten (nicht andere Werwölfe) 🐺⚔️",
  "narrator_select_white_wolf": "Wähle einen Werwolf zu töten 🐺⚔️",
  "narrator_select_wolfshund_choice": "Wähle: Dorfbewohner oder Werwolf? 👥🐺",
  "narrator_selection_invalid": "Ungültige Auswahl ❌",
  "narrator_text_btn": "Erzählertext 📜",
  "narrator_urwolf_text": "Ulwolf, du darfst deine Augen jetzt öffnen.<br>Welche Person möchtest du in einen Werwolf verwandeln?<br>(Der Urwolf zeigt auf eine Person, die Werwolf werden soll)<br>Ulwolf, schließe jetzt deine Augen.<br>Ich gehe jetzt herum und tippe die infizierte Person an.<br>(Erzähler geht rum und tippt die infizierte Person an)<br>Die Person die ich angetippt habe wird in der nächsten Nacht zum Werwolf.<br>Sie verliert ihre andere Rolle. 🐺🩸",
  "narrator_waisenkind_text": "Waisenkind du darfst jetzt deine Augen öffnen.<br>Waisenkind such dir ein Vorbild bei dem du seine Arbeit erlernen willst.<br>(Das Waisenkind zeigt auf eine Person)<br>Ich zeige dir jetzt die Rolle deines Vorbilds<br>(Der Erzähler zeigt die Rolle des Vorbilds)<br>Falls dein Vorbild in der Nacht aufwacht darfst du mit aufwachen und Entscheidungen mitentscheiden.<br>Waisenkind du darfst jetzt deine Augen schließen. 👶🎭",
  "narrator_werwolf_text_1": "Werwölfe, ihr dürft jetzt eure Augen öffnen.<br>Sucht euch eine Person aus, die ihr fressen wollt.<br>(Die Werwölfe einigen sich auf ein Opfer)<br>Werwölfe, schließt jetzt eure Augen. 🐺🌙",
  "narrator_werwolf_text_2": "Werwölfe, ihr dürft jetzt eure Augen öffnen.<br>Sucht euch eine Person aus, die ihr fressen wollt.<br>(Die Werwölfe einigen sich auf ein Opfer)<br>Werwölfe, schließt jetzt eure Augen. 🐺🌙",
  "narrator_win_angel_end": "Der Engel hat gewonnen! 😇🏆",
  "narrator_win_bitter_old_man_end": "Der verbitterte Greis hat gewonnen! (Gegnergruppe eliminiert) 👴🏆",
  "narrator_win_check": "Gewinn-Bedingung wird geprüft... 🔎",
  "narrator_win_lovers_end": "Die Verliebten haben gewonnen! 💑🏆",
  "narrator_win_piper_end": "Der Flötenspieler hat gewonnen! 🎶🏆",
  "narrator_win_villagers_end": "Die Dorfbewohner haben gewonnen! 🏘️🏆",
  "narrator_win_werewolves_end": "Die Werwölfe haben gewonnen! 🐺🏆",
  "narrator_win_white_wolf_end": "Der weiße Werwolf hat allein gewonnen! 🐺⚪🏆",
  "next": "Weiter ➡️",
  "next_player": "Nächster Spieler ▶️",
  "next_to_role_selection": "Weiter zur Rollenauswahl 🎭",
  "night_alpha_wolf_title": "Verwandle jemanden 🐺",
  "night_big_bad_wolf_title": "2. Opfer ⚔️",
  "night_bitter_old_man_selected": "Gewählt: {count} / {total} ✅",
  "night_bitter_old_man_title": "Wähle die Hälfte 1/2 ⚖️",
  "night_cupid_title": "Wähle 2 Verliebte 💘",
  "night_enchanted_look": "Verzauberte, schaut euch an, wer ebenfalls verzaubert ist. ✨👀",
  "night_fox_no_werewolf": "Keiner der Drei ist ein Werwolf. Du hast deine Fähigkeit verloren. ❌🦊",
  "night_fox_title": "Wähle eine Person 🦊",
  "night_fox_werewolf_found": "Einer der Drei ist ein Werwolf! ✅🐺",
  "night_healer_title": "Wähle jemanden 🩺",
  "night_homeless_title": "Wo übernachtest du? 🛌",
  "night_jester_title": "Wähle eine Rolle 🤡",
  "night_lovers_look": "Verliebte, schaut euch an, wer euer Partner ist. 💑👀",
  "night_orphan_model": "Vorbild: {name} - Rolle: {role} 👶➡️🎭",
  "night_orphan_title": "Wähle ein Vorbild 👶",
  "night_piper_selected": "Gewählt: {count} / 2 ✅",
  "night_piper_title": "Wähle 2 Personen 🎶✨",
  "night_pure_soul_revealed": "Reine Seele hat sich zu erkennen gegeben. 😇",
  "night_seer_reveal": "Rolle aufdecken 🔍",
  "night_seer_title": "Wähle eine Person 🔮",
  "night_siblings_title": "Schaut euch an, wer eure Geschwister sind. 👪",
  "night_thief_title": "Wähle eine Karte 🃏",
  "night_urwolf_infected": "Infizierung wurde durchgeführt. 🐺🩸",
  "night_werewolves_title": "Wähle ein Opfer 🐺⚔️",
  "night_white_wolf_title": "Töte einen Werwolf ⚔️",
  "night_wild_child_title": "Wähle dein Vorbild 👶",
  "night_witch_heal": "Heilen 🧪",
  "night_witch_heal_used": "Heiltrank verbraucht ❌🧪",
  "night_witch_healed": "Geheilt ❤️‍🩹",
  "night_witch_poison": "Vergiften ☠️",
  "night_witch_poison_used": "Gifttrank verbraucht ❌☠️",
  "night_witch_title": "Hexe 🧙‍♀️",
  "night_witch_victim": "Opfer der Werwölfe: 💀",
  "night_wolfhound_title": "Wähle deine Seite 🐶",
  "night_wolfhound_villager": "Dorfbewohner 🏘️",
  "night_wolfhound_werewolf": "Werwolf 🐺",
  "orphan": "Waisenkind 👶",
  "overview": "Zur Übersicht 🗂️",
  "overview_instruction": "Tippe auf einen Namen, um den Spielerstatus (tot oder lebendig) zu ändern. 👆💀✅",
  "overview_title": "Spielübersicht 📋",
  "pause_button": "Pause ⏸️",
  "pause_continue": "Weiter ▶️",
  "pause_home": "Zur Startseite 🏠",
  "pause_modal_title": "Spiel pausiert ⏸️",
  "pause_restart": "Neustart 🔄",
  "player_entry_desc": "Gib die Spielernamen ein (jeder Name in einer neuen Zeile). 📝",
  "player_entry_error_duplicate": "Doppelte Namen sind nicht erlaubt. Bitte korrigiere deine Eingabe. ⚠️",
  "player_entry_error_min_players": "Es müssen mindestens 4 Spieler sein. 👥👥",
  "player_entry_placeholder": "Spieler 1\nSpieler 2\nSpieler 3\nSpieler 4",
  "player_entry_rule_1": "Mindestens 4 Spieler 4️⃣",
  "player_entry_rule_2": "und keine doppelten Namen. ❌🔁",
  "player_entry_rules": "Regeln: 📜",
  "player_entry_title": "Spieler-Anmeldung 📝",
  "restart": "Neustart 🔁",
  "restart_info": "Rollen und Namen werden gespeichert 💾",
  "reveal_role": "Rolle aufdecken 🔍",
  "role_amor_desc": "Amor erwacht nur einmal in der allerersten Nacht, um zwei Spieler seiner Wahl miteinander zu verkuppeln (eventuell auch sich selbst). Danach schläft er wieder ein. 💘🌙",
  "role_amor_name": "Amor 💘",
  "role_das_wilde_kind_desc": "Das wilde Kind wählt am Anfang des Spiels einen anderen Spieler, der ab dann sein Vorbild wird. Stirbt sein Vorbild, wird das wilde Kind zum Werwolf. 👶➡️🐺",
  "role_das_wilde_kind_name": "Das wilde Kind 👶",
  "role_der_alte_desc": "Der Alte überlebt den ersten Angriff der Werwölfe. Wird er aber vom Dorfgericht zum Opfer bestimmt, durch die Hexe oder den Jäger umgebracht stirbt er. 👴🛡️",
  "role_der_alte_name": "Der Alte 👴",
  "role_der_baerenfuehrer_desc": "Wenn sich der Bärenführer am Morgen in seiner Sitzposition unmittelbar neben einem Werwolf befindet (ausgeschiedene Spieler werden ignoriert), zeigt der Spielleiter dies durch ein Bärenknurren. Ist der Bärenführer vom Urwolf infiziert, knurrt der Spielleiter jeden Morgen. 🐻🔔",
  "role_der_baerenfuehrer_name": "Der Bärenführer 🐻",
  "role_der_engel_desc": "Wenn er in der Abstimmung der ersten Runde eliminiert wird (nicht von den Werwölfen), gewinnt er das Spiel allein. 😇🏆",
  "role_der_engel_name": "Der Engel 😇",
  "role_der_fuchs_desc": "Wenn er in der Nacht aufgerufen wird, wählt er einen Spieler aus und erfährt vom Spielleiter, ob dieser oder einer ihrer beiden Nachbarn ein Werwolf ist oder nicht. Ist bei dem Trio mindestens ein Werwolf dabei, darf er es in der nächsten Nacht ein weiteres Mal versuchen. Ist aber keiner der drei ein Werwolf, verliert er seine Fähigkeit. 🦊🔍",
  "role_der_fuchs_name": "Der Fuchs 🦊",
  "role_der_grosse_boese_werwolf_desc": "Der große böse Wolf ist ein Wolf, der in jeder zweiten Nacht zweimal tötet. Er einigt sich zunächst mit den anderen Wölfen auf ein Opfer, dann wählt er sich allein ein zweites Opfer. 🐺⚔️",
  "role_der_grosse_boese_werwolf_name": "Der große böse Werwolf 🐺",
  "role_der_obdachlose_desc": "Wenn du aufgerufen wirst, wählst du eine Person bei der du übernachten willst. Wenn diese Person in der Nacht von den Werwölfen getötet wird, stirbst du auch. Wenn die Werwölfe dich in der Nacht töten wollen, stirbst du nicht, weil du bei der anderen Person schläfst. 🛌💀",
  "role_der_obdachlose_name": "Der Obdachlose 🛌",
  "role_der_ritter_desc": "Der Ritter infiziert mit seinem rostigen Schwert den Werwolf zu seiner Linken mit Tetanus, wenn er von ihnen in der Nacht gefressen wird. Dieser Werwolf stirbt dann in der folgenden Nacht. 🗡️",
  "role_der_ritter_name": "Der Ritter mit der verrosteten Klinge 🗡️",
  "role_der_stotternde_richter_desc": "Der Spielleiter und der Richter einigen sich in der ersten Nacht auf ein Zeichen. Wenn der Richter nach der regulären Abstimmung des Dorfes und dem Tod eines Spielers dieses Zeichen gibt, führt der Spielleiter sofort noch eine Abstimmung ohne erneute Diskussion durch. 👨‍⚖️🤫",
  "role_der_stotternde_richter_name": "Der stotternde Richter 👨‍⚖️",
  "role_der_verbitterte_greis_desc": "Zu Beginn teilt der Spielleiter anhand eines offensichtlich einsehbaren, binären Kriteriums das Dorf in zwei Gruppen (z. B. Brille/keine Brille, Bart/kein Bart, größer als 170 cm/kleiner als 170 cm, Geschlecht) – der Greis gehört dann zu einer der beiden Gruppen. Sein Ziel, um das Spiel alleine zu gewinnen, ist es die andere Gruppe komplett zu beseitigen. 👴⚖️",
  "role_der_verbitterte_greis_name": "Der verbitterte Greis 👴",
  "role_der_weisse_werwolf_desc": "Der weiße Werwolf wacht jede Runde zusammen mit den anderen Werwölfen auf und verhält sich normal. Zusätzlich wacht er aber jede zweite Runde erneut gesondert auf und kann, wenn er möchte, einen der anderen Werwölfe töten. Sein Ziel ist es, als einziger zu überleben. 🐺⚪",
  "role_der_weisse_werwolf_name": "Der weiße Werwolf ⚪🐺",
  "role_der_wolfshund_desc": "Wenn er vom Spielleiter aufgerufen wird, kann er entscheiden, ob er zum Werwolf werden oder Dorfbewohner bleiben möchte. 🐶🔀",
  "role_der_wolfshund_name": "Der Wolfshund 🐶",
  "role_die_drei_brueder_desc": "Die drei Brüder erwachen zusammen in der ersten Nacht und erkennen sich. Ansonsten sind sie einfache Dorfbewohner. 👬👬",
  "role_die_drei_brueder_name": "Die drei Brüder 👬",
  "role_die_zwei_schwestern_desc": "Die zwei Schwestern erwachen zusammen in der ersten Nacht und erkennen sich. Ansonsten sind sie einfache Dorfbewohner. 👭",
  "role_die_zwei_schwestern_name": "Die zwei Schwestern 👭",
  "role_dieb_desc": "Der Dieb kann in der ersten Runde seine Karte mit der eines anderen tauschen. 🕵️‍♂️🔁",
  "role_dieb_name": "Dieb 🕵️‍♂️",
  "role_dorfbewohner_desc": "Der normale Dorfbewohner hat keine Sonderfähigkeit. 🧑‍🌾",
  "role_dorfbewohner_name": "Dorfbewohner 🧑‍🌾",
  "role_dorfdepp_desc": "Wird der Dorfdepp vom Dorfgericht zum Opfer gewählt, erkennen sie im letzten Moment, dass es sich nur um den Dorfdeppen handelt. Der Dorfdepp bleibt im Spiel, verliert jedoch sein Abstimmungsrecht. 🤡❌🗳️",
  "role_dorfdepp_name": "Dorfdepp 🤡",
  "role_ergebene_magd_desc": "Wenn jemand stirbt kann die ergebene Magd bevor erfahren wird welche Rolle die tote Person hat ihre Rolle mit der, der toten Person tauschen und ihre Rolle weiterspielen. 👩‍🌾🔀",
  "role_ergebene_magd_name": "Die ergebene Magd 👩‍🌾",
  "role_floetenspieler_desc": "Der Flötenspieler ist eine eigene Partei und kann nur alleine das Spiel gewinnen, außer er ist verliebt. In diesem Fall gewinnt er, wenn nur noch er und die geliebte Person im Spiel sind. Er erwacht immer am Ende jeder Nacht und bestimmt zwei Spieler, die er mit seiner Musik verzaubert. Der Flötenspieler gewinnt das Spiel alleine, wenn alle anderen Spieler verzaubert sind. 🎶🪄",
  "role_floetenspieler_name": "Flötenspieler 🎶",
  "role_gaukler_desc": "Der Spielleiter wählt vor dem Start drei zusätzliche Rollen aus, die er offen in die Mitte legt. Zu Beginn jeder Nacht wählt sich der Schauspieler eine dieser Rollen aus und spielt sie bis zur folgenden Nacht. 🤡🎭",
  "role_gaukler_name": "Der Gaukler 🤡",
  "role_heiler_beschuetzer_desc": "Der Heiler erwacht am Anfang jeder Nacht und bestimmt einen Spieler (auch sich selbst), den er vor den Werwölfen beschützen will. Selbst wenn der ausgewählte Spieler von den Werwölfen gebissen wird, stirbt er nicht. Es ist nicht erlaubt, zwei Runden hintereinander denselben Charakter zu schützen, da dieser sonst unsterblich wäre. 🩺🛡️",
  "role_heiler_beschuetzer_name": "Heiler/Beschützer 🩺",
  "role_hexe_desc": "Die Hexe erwacht, nachdem die Werwölfe ihr Opfer ausgesucht haben. Sie hat im Verlauf des gesamten Spiels einen Gift- und einen Heiltrank. Der Spielleiter zeigt der Hexe das Opfer und die Hexe kann es mit ihrem Heiltrank heilen (auch sich selbst), so dass es überlebt. Sie kann aber auch den Gifttrank auf einen anderen Spieler anwenden. Dadurch kann es in einer Nacht keine, einen oder zwei Tote geben. 🧙‍♀️🧪",
  "role_hexe_name": "Hexe 🧙‍♀️",
  "role_jaeger_desc": "Scheidet der Jäger aus dem Spiel aus, feuert er in seinem letzten Lebensmoment noch einen Schuss ab, mit dem er einen Spieler seiner Wahl mit in den Tod reißt. 🔫💥",
  "role_jaeger_name": "Jäger 🔫",
  "role_kleines_maedchen_desc": "Das kleine Mädchen darf nachts in der Werwolf-Phase heimlich blinzeln, um so die Werwölfe zu erkennen. 👧😉",
  "role_kleines_maedchen_name": "Kleines Mädchen 👧",
  "role_reine_seele_desc": "Du wirst noch am Tag aufgerufen und jeder weiß, dass du ein Dorfbewohner bist. 😇",
  "role_reine_seele_name": "Die reine Seele 😇",
  "role_seherin_desc": "Die Seherin erwacht, während alle anderen schlafen, und darf sich eine Person aussuchen, deren Rolle sie sehen möchte. 🔮",
  "role_seherin_name": "Seherin 🔮",
  "role_selection_title": "Rollen auswählen 🎭",
  "role_suendenbock_desc": "Immer wenn es im Dorf zu einer Pattsituation zwischen dem Sündenbock und einer Person während der Abstimmung kommt, trifft es sofort den Sündenbock. Er opfert sich für das Dorf und scheidet aus dem Spiel aus. 🐑⚖️",
  "role_suendenbock_name": "Sündenbock 🐑",
  "role_urwolf_desc": "Er ist ein Werwolf, der einmalig einen Spieler statt zu fressen in einen Werwolf verwandeln kann. Er signalisiert dem Spielleiter heimlich, nach der Entscheidung aller Werwölfe, wenn eine Umwandlung stattfinden soll. 🐺🔁",
  "role_urwolf_name": "Der Urwolf 🐺",
  "role_waisenkind_desc": "Wenn das Waisenkind vom Erzähler aufgerufen wird, wählt es ein Vorbild. Das Waisenkind nimmt die Rolle des Vorbilds an. Spezialfähigkeiten doppeln sich nicht, sondern werden geteilt. 👶➡️🎭",
  "role_waisenkind_name": "Das Waisenkind 👶",
  "role_werwolf_desc": "Die Werwölfe werden nachts vom Spielleiter aufgerufen, erkennen sich und einigen sich auf ein Opfer, welches dann gefressen wird und somit aus dem Spiel ist. 🐺🌙",
  "role_werwolf_name": "Werwölfe 🐺",
  "save": "Speichern 💾",
  "select_exactly_n_roles": "Wähle genau {count} Rollen aus. 🎭",
  "select_first_person": "Wähle die erste Person aus. 1️⃣",
  "select_person_for_maid": "Wähle einen Spieler aus, dem die Magd dienen soll. 👩‍🌾",
  "select_person_to_infect": "Wähle einen Spieler zum Infizieren aus. 🐺➡️",
  "select_role_model": "Wähle ein Vorbild aus. 👤➡️",
  "select_second_person": "Wähle die zweite Person aus. 2️⃣",
  "special_actions": "Spezialaktionen ✨",
  "start_game": "Zum Spiel ▶️",
  "stop": "Stopp ⏹️",
  "thief": "Dieb 🕵️‍♂️",
  "thief_selection_title": "Wähle 2 Rollen für den Dieb 🃏🃏",
  "to_game": "Zum Spiel ▶️",
  "to_homepage": "Zur Startseite 🏠",
  "to_overview": "Zur Spielübersicht 📋",
  "to_role_selection": "Zur Rollenauswahl 🎭",
  "urwolf": "Urwolf 🐺",
  "win_screen_emoji": "🎉",
  "win_screen_home_info": "Kompletter Reset ♻️",
  "win_screen_restart_info": "Zur Rollenauswahl 🔁",
  "with_narrator": "Mit Erzähler spielen 🎙️",
  "without_narrator": "Ohne Erzähler spielen 🚫🎙️"
"""
def format_text_and_save(text, output_file):
    lines = text.splitlines()
    formatted_lines = []

    for line in lines:
        line = line.strip()
        if not line or line.startswith("//"):
            continue
        if ":" in line:
            key, value = line.split(":", 1)
            key = key.strip().strip('"')  # Key ohne Anführungszeichen
            value = value.strip()          # Value bleibt mit Anführungszeichen
            formatted_line = f'    {key}: {value}'  # Vier Leerzeichen vor jeder Zeile
            formatted_lines.append(formatted_line)

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(formatted_lines))

    print(f"Datei '{output_file}' erstellt!")

if __name__ == "__main__":
    output_file = "output.txt"
    format_text_and_save(text, output_file)