export const ROLES_CONFIG = [
  { id: 'dorfbewohner', nameKey: 'role_dorfbewohner_name', descriptionKey: 'role_dorfbewohner_desc' },
  { id: 'werwolf', nameKey: 'role_werwolf_name', descriptionKey: 'role_werwolf_desc' },
  { id: 'hexe', nameKey: 'role_hexe_name', descriptionKey: 'role_hexe_desc' },
  { id: 'seherin', nameKey: 'role_seherin_name', descriptionKey: 'role_seherin_desc' },
  { id: 'jaeger', nameKey: 'role_jaeger_name', descriptionKey: 'role_jaeger_desc' },
  { id: 'amor', nameKey: 'role_amor_name', descriptionKey: 'role_amor_desc' },
  { id: 'dieb', nameKey: 'role_dieb_name', descriptionKey: 'role_dieb_desc' },
  { id: 'der_obdachlose', nameKey: 'role_der_obdachlose_name', descriptionKey: 'role_der_obdachlose_desc' },
  { id: 'waisenkind', nameKey: 'role_waisenkind_name', descriptionKey: 'role_waisenkind_desc' },
  { id: 'kleines_maedchen', nameKey: 'role_kleines_maedchen_name', descriptionKey: 'role_kleines_maedchen_desc' },
  { id: 'heiler_beschuetzer', nameKey: 'role_heiler_beschuetzer_name', descriptionKey: 'role_heiler_beschuetzer_desc' },
  { id: 'suendenbock', nameKey: 'role_suendenbock_name', descriptionKey: 'role_suendenbock_desc' },
  { id: 'dorfdepp', nameKey: 'role_dorfdepp_name', descriptionKey: 'role_dorfdepp_desc' },
  { id: 'der_alte', nameKey: 'role_der_alte_name', descriptionKey: 'role_der_alte_desc' },
  { id: 'floetenspieler', nameKey: 'role_floetenspieler_name', descriptionKey: 'role_floetenspieler_desc' },
  { id: 'der_grosse_boese_werwolf', nameKey: 'role_der_grosse_boese_werwolf_name', descriptionKey: 'role_der_grosse_boese_werwolf_desc' },
  { id: 'urwolf', nameKey: 'role_urwolf_name', descriptionKey: 'role_urwolf_desc' },
  { id: 'der_weisse_werwolf', nameKey: 'role_der_weisse_werwolf_name', descriptionKey: 'role_der_weisse_werwolf_desc' },
  { id: 'der_wolfshund', nameKey: 'role_der_wolfshund_name', descriptionKey: 'role_der_wolfshund_desc' },
  { id: 'das_wilde_kind', nameKey: 'role_das_wilde_kind_name', descriptionKey: 'role_das_wilde_kind_desc' },
  { id: 'reine_seele', nameKey: 'role_reine_seele_name', descriptionKey: 'role_reine_seele_desc' },
  { id: 'der_engel', nameKey: 'role_der_engel_name', descriptionKey: 'role_der_engel_desc' },
  { id: 'die_drei_brueder', nameKey: 'role_die_drei_brueder_name', descriptionKey: 'role_die_drei_brueder_desc' },
  { id: 'die_zwei_schwestern', nameKey: 'role_die_zwei_schwestern_name', descriptionKey: 'role_die_zwei_schwestern_desc' },
  { id: 'der_fuchs', nameKey: 'role_der_fuchs_name', descriptionKey: 'role_der_fuchs_desc' },
  { id: 'ergebene_magd', nameKey: 'role_ergebene_magd_name', descriptionKey: 'role_ergebene_magd_desc' },
  { id: 'der_baerenfuehrer', nameKey: 'role_der_baerenfuehrer_name', descriptionKey: 'role_der_baerenfuehrer_desc' },
  { id: 'der_ritter', nameKey: 'role_der_ritter_name', descriptionKey: 'role_der_ritter_desc' },
  { id: 'der_verbitterte_greis', nameKey: 'role_der_verbitterte_greis_name', descriptionKey: 'role_der_verbitterte_greis_desc' },
  { id: 'gaukler', nameKey: 'role_gaukler_name', descriptionKey: 'role_gaukler_desc' },
  { id: 'der_stotternde_richter', nameKey: 'role_der_stotternde_richter_name', descriptionKey: 'role_der_stotternde_richter_desc' },
];

export const NARRATOR_TEXTS_KEYS: { [key: string]: { roleId: string; roleNameKey: string; textKey: string }[] } = {
  '1': [
    { roleId: 'waisenkind', roleNameKey: 'role_waisenkind_name', textKey: 'narrator_waisenkind_text' },
    { roleId: 'dieb', roleNameKey: 'role_dieb_name', textKey: 'narrator_dieb_text' },
    { roleId: 'gaukler', roleNameKey: 'role_gaukler_name', textKey: 'narrator_gaukler_text_1' },
    { roleId: 'der_verbitterte_greis', roleNameKey: 'role_der_verbitterte_greis_name', textKey: 'narrator_der_verbitterte_greis_text' },
    { roleId: 'amor', roleNameKey: 'role_amor_name', textKey: 'narrator_amor_text' },
    { roleId: 'der_wolfshund', roleNameKey: 'role_der_wolfshund_name', textKey: 'narrator_der_wolfshund_text' },
    { roleId: 'die_drei_brueder', roleNameKey: 'role_die_drei_brueder_name', textKey: 'narrator_die_drei_brueder_text' },
    { roleId: 'die_zwei_schwestern', roleNameKey: 'role_die_zwei_schwestern_name', textKey: 'narrator_die_zwei_schwestern_text' },
    { roleId: 'das_wilde_kind', roleNameKey: 'role_das_wilde_kind_name', textKey: 'narrator_das_wilde_kind_text' },
    { roleId: 'der_stotternde_richter', roleNameKey: 'role_der_stotternde_richter_name', textKey: 'narrator_der_stotternde_richter_text' },
    { roleId: 'seherin', roleNameKey: 'role_seherin_name', textKey: 'narrator_seherin_text_1' },
    { roleId: 'heiler_beschuetzer', roleNameKey: 'role_heiler_beschuetzer_name', textKey: 'narrator_heiler_beschuetzer_text_1' },
    { roleId: 'werwolf', roleNameKey: 'role_werwolf_name', textKey: 'narrator_werwolf_text_1' },
    { roleId: 'urwolf', roleNameKey: 'role_urwolf_name', textKey: 'narrator_urwolf_text' },
    { roleId: 'hexe', roleNameKey: 'role_hexe_name', textKey: 'narrator_hexe_text_1' },
    { roleId: 'floetenspieler', roleNameKey: 'role_floetenspieler_name', textKey: 'narrator_floetenspieler_text_1' },
    { roleId: 'der_obdachlose', roleNameKey: 'role_der_obdachlose_name', textKey: 'narrator_der_obdachlose_text_1' },
    { roleId: 'der_fuchs', roleNameKey: 'role_der_fuchs_name', textKey: 'narrator_der_fuchs_text_1' },
  ],
  '2': [
    { roleId: 'gaukler', roleNameKey: 'role_gaukler_name', textKey: 'narrator_gaukler_text_2' },
    { roleId: 'seherin', roleNameKey: 'role_seherin_name', textKey: 'narrator_seherin_text_2' },
    { roleId: 'heiler_beschuetzer', roleNameKey: 'role_heiler_beschuetzer_name', textKey: 'narrator_heiler_beschuetzer_text_2' },
    { roleId: 'werwolf', roleNameKey: 'role_werwolf_name', textKey: 'narrator_werwolf_text_2' },
    { roleId: 'der_grosse_boese_werwolf', roleNameKey: 'role_der_grosse_boese_werwolf_name', textKey: 'narrator_der_grosse_boese_werwolf_text' },
    { roleId: 'der_weisse_werwolf', roleNameKey: 'role_der_weisse_werwolf_name', textKey: 'narrator_der_weisse_werwolf_text' },
    { roleId: 'hexe', roleNameKey: 'role_hexe_name', textKey: 'narrator_hexe_text_2' },
    { roleId: 'floetenspieler', roleNameKey: 'role_floetenspieler_name', textKey: 'narrator_floetenspieler_text_2' },
    { roleId: 'der_obdachlose', roleNameKey: 'role_der_obdachlose_name', textKey: 'narrator_der_obdachlose_text_2' },
    { roleId: 'der_fuchs', roleNameKey: 'role_der_fuchs_name', textKey: 'narrator_der_fuchs_text_2' },
  ],
};